# Generated by Django 5.1.4 on 2026-01-06 04:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('judge', 'Judge Prompt'), ('storyteller', 'Storyteller Prompt'), ('test', 'Test Prompt')], db_index=True, help_text='Type of prompt (judge, storyteller, etc.)', max_length=50)),
                ('version', models.IntegerField(help_text='Version number (1, 2, 3, ...)')),
                ('description', models.CharField(blank=True, help_text='User-friendly description of this version', max_length=255)),
                ('prompt_text', models.TextField(help_text='The actual prompt content')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this prompt is currently active for API calls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['prompt_type', '-version'],
                'indexes': [models.Index(fields=['prompt_type', 'is_active'], name='game_prompt_prompt__e8e48e_idx')],
                'unique_together': {('prompt_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('original_text', models.TextField(help_text='Original output from storyteller LLM')),
                ('refined_text', models.TextField(help_text='Final output after judge review')),
                ('was_modified', models.BooleanField(db_index=True, default=False, help_text='True if judge made changes, False if passed through unchanged')),
                ('prompt_used', models.ForeignKey(blank=True, help_text='Which judge prompt was active during this request', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.prompt')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'was_modified'], name='game_auditl_timesta_6f922b_idx')],
            },
        ),
    ]
