# Generated by Django 5.1.4 on 2026-01-07 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt_type',
            field=models.CharField(choices=[('judge', 'Judge Prompt'), ('system', 'System/Adventure Prompt'), ('test', 'Test Prompt')], db_index=True, help_text='Type of prompt (judge, storyteller, etc.)', max_length=50),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this configuration preset', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this configuration')),
                ('storyteller_model', models.CharField(help_text='Model to use for story generation (e.g., qwen3:4b)', max_length=100)),
                ('judge_model', models.CharField(help_text='Model to use for judge validation (e.g., claude-haiku-4-5)', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether this configuration is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adventure_prompt', models.ForeignKey(help_text='System/Adventure prompt to use', limit_choices_to={'prompt_type': 'system'}, on_delete=django.db.models.deletion.PROTECT, related_name='configs_as_adventure', to='game.prompt')),
                ('judge_prompt', models.ForeignKey(help_text='Judge prompt to use for validation', limit_choices_to={'prompt_type': 'judge'}, on_delete=django.db.models.deletion.PROTECT, related_name='configs_as_judge', to='game.prompt')),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
                'indexes': [models.Index(fields=['is_active'], name='game_config_is_acti_728394_idx')],
            },
        ),
    ]
