# Generated by Django 5.1.4 on 2026-01-07 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_prompt_prompt_type_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='adventure_prompt',
            field=models.ForeignKey(help_text='Adventure/story prompt to use (any non-judge prompt)', on_delete=django.db.models.deletion.PROTECT, related_name='configs_as_adventure', to='game.prompt'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_type',
            field=models.CharField(db_index=True, help_text="Type of prompt: 'judge' or adventure name (e.g., 'arctic-alien', 'haunted-house')", max_length=50),
        ),
    ]
