# Generated by Django 5.1.4 on 2026-01-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_configuration_adventure_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, help_text='Cache key (session_hash-turn_number)', max_length=255, unique=True)),
                ('response_text', models.TextField(help_text='The cached response from the base storyteller')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this cache entry was created')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cache_key', 'created_at'], name='game_respon_cache_k_4e8781_idx')],
            },
        ),
    ]
