# Generated by Django on 2026-01-08

from django.db import migrations, models


def backfill_judge_timeout(apps, schema_editor):
    """
    Backfill judge_timeout with default value of 30 seconds for all existing configurations.
    """
    Configuration = apps.get_model('game', 'Configuration')
    Configuration.objects.all().update(judge_timeout=30)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_responsecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='judge_timeout',
            field=models.IntegerField(default=30, help_text='Timeout in seconds for judge validation (default: 30)'),
        ),
        migrations.RunPython(backfill_judge_timeout, reverse_code=migrations.RunPython.noop),
    ]
