# Generated by Django on 2026-01-08

from django.db import migrations, models


def backfill_storyteller_timeout(apps, schema_editor):
    """
    Backfill storyteller_timeout with default value of 30 seconds for all existing configurations.
    """
    Configuration = apps.get_model('game', 'Configuration')
    Configuration.objects.all().update(storyteller_timeout=30)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_configuration_judge_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='storyteller_timeout',
            field=models.IntegerField(default=30, help_text='Timeout in seconds for storyteller generation (default: 30)'),
        ),
        migrations.RunPython(backfill_storyteller_timeout, reverse_code=migrations.RunPython.noop),
    ]
