# Generated by Django 5.1.4 on 2026-02-15 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_user_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiprovider',
            name='provider_type',
            field=models.CharField(choices=[('ollama', 'Ollama Server'), ('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)'), ('openrouter', 'OpenRouter')], help_text='Type of API provider', max_length=50),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='classifier_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for classifier (default: 60)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='storyteller_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for storyteller generation (default: 60)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='turn_correction_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for turn correction (default: 60)'),
        ),
        migrations.AlterField(
            model_name='judgestep',
            name='classifier_model',
            field=models.ForeignKey(blank=True, help_text='Model for classification', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='judge_steps_as_classifier', to='game.llmmodel'),
        ),
        migrations.AlterField(
            model_name='judgestep',
            name='classifier_question',
            field=models.TextField(default='Does this turn have issues that make it invalid?', help_text='Question to ask classifier about the turn'),
        ),
        migrations.AlterField(
            model_name='judgestep',
            name='classifier_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for classification'),
        ),
        migrations.AlterField(
            model_name='judgestep',
            name='compare_model',
            field=models.ForeignKey(help_text='Model for comparing turns', on_delete=django.db.models.deletion.PROTECT, related_name='judge_steps_as_comparator', to='game.llmmodel'),
        ),
        migrations.AlterField(
            model_name='judgestep',
            name='compare_prompt',
            field=models.ForeignKey(help_text='Judge prompt to compare original vs rewritten turn', limit_choices_to={'prompt_type': 'judge'}, on_delete=django.db.models.deletion.PROTECT, related_name='judge_steps_as_comparator', to='game.prompt'),
        ),
        migrations.AlterField(
            model_name='judgestep',
            name='compare_question',
            field=models.TextField(default='Is the revised turn better and more valid than the original?', help_text='Question to ask when comparing original vs rewritten turn'),
        ),
        migrations.AlterField(
            model_name='judgestep',
            name='compare_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for comparison'),
        ),
        migrations.AlterField(
            model_name='judgestep',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='judgestep',
            name='rewrite_instruction',
            field=models.TextField(blank=True, default='Re-write this text to be a valid choose your own adventure turn following all the rules:', help_text='Additional instruction appended to rewrite request'),
        ),
        migrations.AlterField(
            model_name='judgestep',
            name='rewrite_model',
            field=models.ForeignKey(help_text='Model for rewriting turns', on_delete=django.db.models.deletion.PROTECT, related_name='judge_steps_as_rewriter', to='game.llmmodel'),
        ),
        migrations.AlterField(
            model_name='judgestep',
            name='rewrite_prompt',
            field=models.ForeignKey(help_text='Turn correction prompt for rewriting', limit_choices_to={'prompt_type': 'turn-correction'}, on_delete=django.db.models.deletion.PROTECT, related_name='judge_steps_as_rewriter', to='game.prompt'),
        ),
        migrations.AlterField(
            model_name='judgestep',
            name='rewrite_timeout',
            field=models.IntegerField(default=60, help_text='Timeout in seconds for rewrite generation'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(db_index=True, default='default', help_text="Descriptive name for this prompt (e.g., 'haunted-house', 'correct_refusal')", max_length=100),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_type',
            field=models.CharField(db_index=True, help_text='Category: adventure, turn-correction, game-ending, classifier, judge', max_length=50),
        ),
    ]
