# Generated by Django 5.1.4 on 2026-02-16 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_apiprovider_provider_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the TTS audio', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the TTS request was created')),
                ('text', models.TextField(help_text='Text to be converted to speech')),
                ('text_hash', models.CharField(db_index=True, help_text='SHA-256 hash of text for deduplication', max_length=64)),
                ('voice', models.CharField(choices=[('alloy', 'Alloy'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('shimmer', 'Shimmer')], default='alloy', help_text='Voice to use for TTS', max_length=20)),
                ('model', models.CharField(default='tts-1', help_text='TTS model (tts-1 or tts-1-hd)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current status of the TTS generation', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Path to the generated audio file relative to MEDIA_ROOT', max_length=500, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duration of the audio in seconds', null=True)),
                ('error_text', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['text_hash', 'voice', 'model'], name='game_ttsaud_text_ha_1092c6_idx'), models.Index(fields=['status', '-created_at'], name='game_ttsaud_status_753850_idx')],
            },
        ),
    ]
