# Generated by Django 5.1.4 on 2026-02-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_ttsaudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_model', models.CharField(choices=[('tts-1', 'TTS-1 (Fast, Standard Quality)'), ('tts-1-hd', 'TTS-1-HD (Slower, High Quality)')], default='tts-1', help_text='OpenAI TTS model to use', max_length=50)),
                ('openai_voice', models.CharField(choices=[('alloy', 'Alloy (Neutral)'), ('echo', 'Echo (Male)'), ('fable', 'Fable (Expressive)'), ('onyx', 'Onyx (Deep Male)'), ('nova', 'Nova (Female)'), ('shimmer', 'Shimmer (Soft Female)')], default='alloy', help_text='Default voice for OpenAI TTS', max_length=20)),
                ('audio_retention_days', models.IntegerField(default=7, help_text='Days to keep TTS audio files before automatic cleanup')),
                ('auto_cleanup_enabled', models.BooleanField(default=True, help_text='Automatically clean up old audio files during generation')),
                ('enabled', models.BooleanField(default=True, help_text='Enable TTS functionality')),
                ('max_text_length', models.IntegerField(default=4096, help_text='Maximum text length for TTS (OpenAI limit: 4096)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TTS Settings',
                'verbose_name_plural': 'TTS Settings',
            },
        ),
    ]
