# Generated by Django 5.1.4 on 2026-01-17 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_gamesession_conversation_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, help_text='UUID for this conversation', max_length=36, unique=True)),
                ('title', models.CharField(blank=True, default='New Conversation', help_text='Human-readable title for this conversation', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (inventory, game state, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='Who sent this message', max_length=10)),
                ('content', models.TextField(help_text='The message content')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for this message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='game_chatme_convers_1d4646_idx')],
            },
        ),
    ]
