# Generated by Django 5.1.4 on 2026-01-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_sttrecording'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveIndex(
            model_name='configuration',
            name='game_config_is_acti_728394_idx',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='is_active',
        ),
    ]
