# Generated by Django 5.1.4 on 2026-01-17 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_configuration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='game_ending_prompt',
            field=models.ForeignKey(blank=True, help_text='Prompt to use when game ends due to death/failure', limit_choices_to={'prompt_type': 'game-ending'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configs_as_game_ending', to='game.prompt'),
        ),
    ]
