# Generated by Django 5.1.4 on 2026-01-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_configuration_game_ending_prompt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseCache',
        ),
    ]
